# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1camZEVGFVd5kHeRiJKL5th2fkgAU7ret
"""

import streamlit as st
from googletrans import Translator

def translate_to_english(hebrew_text):
    translator = Translator()
    translation = translator.translate(hebrew_text, src='he', dest='ar')
    return translation.text

st.title("Hebrew to Arabic Translation App")

hebrew_text = st.text_area("Enter a Hebrew sentence:")
if st.button("Translate"):
    if hebrew_text:
        english_translation = translate_to_english(hebrew_text)
        st.write(f"English Translation: {english_translation}")
    else:
        st.warning("Please enter a Hebrew sentence.")

st.write("Note: This is a basic translation app and may not be perfect for complex sentences.")